"""
Solve record management endpoints.
CRUD operations for individual solve attempts.
"""

import logging
from fastapi import APIRouter, Depends, Query, status

from ..db import get_db
from ..models import SolveRecordModel
from ..services.solve import SolveService, solve_to_model
from sqlalchemy.orm import Session

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/api", tags=["solves"])


@router.get(
    "/profiles/{profile_id}/solves",
    response_model=list[SolveRecordModel],
    status_code=status.HTTP_200_OK,
    summary="Get all solve records for a profile",
)
async def get_profile_solves(
    profile_id: int,
    limit: int = Query(100, ge=1, le=1000),
    offset: int = Query(0, ge=0),
    db: Session = Depends(get_db),
) -> list[SolveRecordModel]:
    """
    Get all solve records for a profile (most recent first).
    
    By default excludes DNF (Did Not Finish) and DNS (Did Not Start) solves.
    
    **Query Parameters:**
    - `limit`: Maximum number of records to return (default: 100, max: 1000)
    - `offset`: Number of records to skip for pagination (default: 0)
    
    **Response:**
    ```json
    [
        {
            "id": 1,
            "profile_id": 1,
            "time_ms": 45320,
            "num_moves": 52,
            "scramble": "R U R' U'...",
            "solution": "R U R' U'...",
            "solver_used": "manual",
            "confidence": 1.0,
            "is_dnf": false,
            "is_dns": false,
            "notes": "Good solve",
            "created_at": "2024-01-15T10:30:00"
        }
    ]
    ```
    """
    solves = SolveService.get_profile_solves(db, profile_id, limit, offset)
    return [solve_to_model(solve) for solve in solves]


@router.get(
    "/solves/{solve_id}",
    response_model=SolveRecordModel,
    status_code=status.HTTP_200_OK,
    summary="Get a solve record",
)
async def get_solve(
    solve_id: int,
    db: Session = Depends(get_db),
) -> SolveRecordModel:
    """
    Get a specific solve record by ID.
    """
    solve = SolveService.get_solve(db, solve_id)
    return solve_to_model(solve)


@router.post(
    "/solves",
    response_model=SolveRecordModel,
    status_code=status.HTTP_201_CREATED,
    summary="Create a new solve record",
)
async def create_solve(
    solve_data: SolveRecordModel,
    db: Session = Depends(get_db),
) -> SolveRecordModel:
    """
    Record a new solve attempt.
    
    **Request:**
    ```json
    {
        "profile_id": 1,
        "time_ms": 45320,
        "num_moves": 52,
        "scramble": "R U R' U'...",
        "solution": "R U R' U'...",
        "solver_used": "manual",
        "confidence": 1.0,
        "is_dnf": false,
        "is_dns": false,
        "notes": "Good solve, could improve F2L"
    }
    ```
    
    **Response:** (201 Created)
    ```json
    {
        "id": 1,
        "profile_id": 1,
        "time_ms": 45320,
        "num_moves": 52,
        "scramble": "R U R' U'...",
        "solution": "R U R' U'...",
        "solver_used": "manual",
        "confidence": 1.0,
        "is_dnf": false,
        "is_dns": false,
        "notes": "Good solve, could improve F2L",
        "created_at": "2024-01-15T10:30:00"
    }
    ```
    
    **Solver Types:**
    - `manual`: User entered manually or with app
    - `kociemba`: Kociemba optimal solver
    - `human`: Human speedcuber solve
    - `algorithm`: Generated by specific algorithm
    
    **Time Format:**
    All times are in milliseconds (ms). For example:
    - 45320 ms = 45.32 seconds
    - 1234 ms = 1.234 seconds
    
    **Move Count:**
    Number of individual face/slice/rotation moves in the solution.
    
    **Confidence:**
    Float between 0.0 and 1.0 representing solver confidence in the solution.
    Manual solves typically have confidence 1.0.
    """
    solve = SolveService.create_solve(
        db,
        solve_data.dict(exclude_unset=True),
    )
    return solve_to_model(solve)


@router.delete(
    "/solves/{solve_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    summary="Delete a solve record",
)
async def delete_solve(
    solve_id: int,
    db: Session = Depends(get_db),
) -> None:
    """
    Delete a solve record.
    """
    SolveService.delete_solve(db, solve_id)
