"""
CubeAI - Cubie Converter

Converts between:
    CubeState  (sticker grid)
    CubieState (physical piece + orientation)

Design
------
* Single source of truth for every constant.
  cubeState.py    -> FACE_TO_COLOR, FACE_NAMES, CubeState
  cubie.py        -> CornerCubie, EdgeCubie, CubieState
  cubeValidator   -> CORNER_FACELETS, EDGE_FACELETS,
                     CORNER_COLORS (frozensets), EDGE_COLORS (frozensets)
  move.py         -> apply_algorithm, apply_algorithm_cubie, invert_algorithm

* Orientation convention is an exact mirror of CubeValidator.
  _corner_orientation / _edge_orientation are copied verbatim.

* CORNER_PERM_TABLE drives cubiestate_to_cubestate reconstruction.
  Generated by BFS over all reachable cube states; zero conflicts.
  Key: (piece_is_D_layer, slot_is_D_layer, orientation)

* CORNER_FACELET_CANONICAL — the correct canonical tuple for each corner
  PIECE is derived directly from the face geometry (CORNER_FACELETS),
  NOT from cubie.py CORNER_COLORS whose UFR entry uses a different
  sticker ordering.  All other slots agree, but relying on geometry
  makes the code robust to any future ordering changes.

* EDGE_FACELET_CANONICAL — similarly derived from EDGE_FACELETS.

Color scheme (fixed in cubeState.py / cubeValidator.py):

    U=white  R=red    F=green  D=yellow  L=orange  B=blue

Corner slot order (cubeValidator CORNER_FACELETS):

    0 UFR  1 URB  2 UBL  3 ULF
    4 DFR  5 DRB  6 DBL  7 DLF

Edge slot order (cubeValidator EDGE_FACELETS):

     0 UF   1 UR   2 UB   3 UL
     4 FR   5 BR   6 BL   7 FL
     8 DF   9 DR  10 DB  11 DL

Pipeline:

    Scanner -> CubeState -> cubieConverter -> CubieState -> Solver
"""

from __future__ import annotations

import os
import sys
from typing import TYPE_CHECKING, Any, Optional

# ---------------------------------------------------------------------------
# Path setup
# ---------------------------------------------------------------------------

CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
if CURRENT_DIR not in sys.path:
    sys.path.insert(0, CURRENT_DIR)

# ---------------------------------------------------------------------------
# TYPE_CHECKING — gives Pylance real types without runtime conflicts
# ---------------------------------------------------------------------------

if TYPE_CHECKING:
    from cubeState import CubeState
    from cubie import CubieState, CornerCubie, EdgeCubie
    from cubeValidator import CubeValidator

# ---------------------------------------------------------------------------
# Runtime imports
# ---------------------------------------------------------------------------

_CubeState:    Any = None
_CubieState:   Any = None
_CornerCubie:  Any = None
_EdgeCubie:    Any = None
_CubeValidator: Any = None

CUBE_STATE_IMPORT_ERROR:     Optional[str] = None
CUBIE_IMPORT_ERROR:          Optional[str] = None
CUBE_VALIDATOR_IMPORT_ERROR: Optional[str] = None

_FACE_TO_COLOR: dict[str, str] = {
    "U": "white", "R": "red",    "F": "green",
    "D": "yellow","L": "orange", "B": "blue",
}
_FACE_NAMES: tuple[str, ...] = ("U", "R", "F", "D", "L", "B")

try:
    from cubeState import (                        # type: ignore[no-redef]
        CubeState     as _CubeState,
        FACE_TO_COLOR as _FACE_TO_COLOR,             # type: ignore[assignment]
        FACE_NAMES    as _FACE_NAMES,                # type: ignore[assignment]
    )
except ImportError as _exc:
    CUBE_STATE_IMPORT_ERROR = str(_exc)

try:
    from cubie import (                        # type: ignore[no-redef]
        CubieState  as _CubieState,
        CornerCubie as _CornerCubie,
        EdgeCubie   as _EdgeCubie,
    )
except ImportError as _exc:
    CUBIE_IMPORT_ERROR = str(_exc)

# cubeValidator constants
CORNER_FACELETS: Any = None
EDGE_FACELETS:   Any = None
VAL_CORNER_COLORS: Any = None   # tuple of frozensets
VAL_EDGE_COLORS:   Any = None   # tuple of frozensets

try:
    from cubeValidator import (                        # type: ignore[no-redef]
        CubeValidator  as _CubeValidator,
        CORNER_FACELETS,
        EDGE_FACELETS,
        CORNER_COLORS  as VAL_CORNER_COLORS,
        EDGE_COLORS    as VAL_EDGE_COLORS,
    )
except ImportError as _exc:
    CUBE_VALIDATOR_IMPORT_ERROR = str(_exc)

# move.py — optional; tests skip gracefully when absent
_move_module: Any = None
try:
    import move as _move_module
except ImportError:
    pass


# ===========================================================================
# Geometry-derived canonical tuples
# ===========================================================================

def _build_corner_canonical() -> tuple[tuple[str, str, str], ...]:
    if CORNER_FACELETS is None:
        return (
            ("white",  "green",  "red"),
            ("white",  "red",    "blue"),
            ("white",  "blue",   "orange"),
            ("white",  "orange", "green"),
            ("yellow", "green",  "red"),
            ("yellow", "red",    "blue"),
            ("yellow", "blue",   "orange"),
            ("yellow", "orange", "green"),
        )
    return tuple(
        tuple(_FACE_TO_COLOR[face] for face, _, _ in facelets)   # type: ignore[misc]
        for facelets in CORNER_FACELETS
    )

def _build_edge_canonical() -> tuple[tuple[str, str], ...]:
    if EDGE_FACELETS is None:
        return (
            ("white",  "green"),  ("white",  "red"),
            ("white",  "blue"),   ("white",  "orange"),
            ("green",  "red"),    ("blue",   "red"),
            ("blue",   "orange"), ("green",  "orange"),
            ("yellow", "green"),  ("yellow", "red"),
            ("yellow", "blue"),   ("yellow", "orange"),
        )
    return tuple(
        tuple(_FACE_TO_COLOR[face] for face, _, _ in facelets)   # type: ignore[misc]
        for facelets in EDGE_FACELETS
    )

CORNER_PIECE_CANONICAL: tuple[tuple[str, str, str], ...] = _build_corner_canonical()
EDGE_PIECE_CANONICAL:   tuple[tuple[str, str], ...]      = _build_edge_canonical()


# ===========================================================================
# Pre-computed O(1) Lookup Dictionaries
# ===========================================================================

def _build_lookups() -> tuple[dict[frozenset[str], int], dict[frozenset[str], int]]:
    corner_lookup = {}
    edge_lookup = {}
    if VAL_CORNER_COLORS is not None:
        for idx, colors in enumerate(VAL_CORNER_COLORS):
            corner_lookup[frozenset(colors)] = idx
    if VAL_EDGE_COLORS is not None:
        for idx, colors in enumerate(VAL_EDGE_COLORS):
            edge_lookup[frozenset(colors)] = idx
    return corner_lookup, edge_lookup

_CORNER_LOOKUP, _EDGE_LOOKUP = _build_lookups()


# ===========================================================================
# Corner reconstruction permutation table
# ===========================================================================

CORNER_PERM_TABLE: dict[tuple[bool, bool, int], tuple[int, int, int]] = {
    (False, False, 0): (0, 1, 2),
    (False, False, 1): (2, 0, 1),
    (False, False, 2): (1, 2, 0),
    (False, True,  0): (0, 2, 1),
    (False, True,  1): (2, 1, 0),
    (False, True,  2): (1, 0, 2),
    (True,  False, 0): (0, 2, 1),
    (True,  False, 1): (1, 0, 2),
    (True,  False, 2): (2, 1, 0),
    (True,  True,  0): (0, 1, 2),
    (True,  True,  1): (1, 2, 0),
    (True,  True,  2): (2, 0, 1),
}


# ===========================================================================
# Import guard
# ===========================================================================

def _require_imports() -> None:
    if _CubeState is None:
        raise RuntimeError(
            f"cubeState.py could not be imported: {CUBE_STATE_IMPORT_ERROR}"
        )
    if _CubieState is None:
        raise RuntimeError(
            f"cubie.py could not be imported: {CUBIE_IMPORT_ERROR}"
        )
    if _CubeValidator is None:
        raise RuntimeError(
            f"cubeValidator.py could not be imported: "
            f"{CUBE_VALIDATOR_IMPORT_ERROR}"
        )


# ===========================================================================
# Orientation helpers — Robust handling for single face rotations
# ===========================================================================

def _corner_orientation(colors: list[str], facelets: Any) -> int:
    """
    Computes corner orientation (0, 1, or 2).
    Determined by finding where the U/D primary color lands on the facelet structure.
    """
    ud_index = next(
        (i for i, c in enumerate(colors) if c in ("white", "yellow")), -1
    )
    if ud_index == -1:
        return 0
    
    # U- and D-layer facelet definitions have opposite handedness.
    if facelets[0][0] == "U":
        return ud_index
    return (-ud_index) % 3


def _edge_orientation(colors: list[str], facelets: Any) -> int:
    """
    Computes edge orientation (0 or 1) from the cubie's canonical sticker order.

    This is the convention used by the cubie move engine: U/D/R/L turns
    preserve the canonical order and F/B turns reverse it.
    """
    piece_idx = _EDGE_LOOKUP.get(frozenset(colors))
    if piece_idx is None:
        return 0
    return 0 if tuple(colors) == EDGE_PIECE_CANONICAL[piece_idx] else 1


# ===========================================================================
# CubeState → CubieState
# ===========================================================================

def cubestate_to_cubiestate(cube: "CubeState") -> "CubieState":
    """
    Convert a CubeState (sticker grid) to a CubieState (piece + orientation).
    Performs O(1) lookups and validates topological consistency via CubeValidator.
    """
    _require_imports()

    # Rebuild lookups dynamically if they were uninitialized at module load time
    global _CORNER_LOOKUP, _EDGE_LOOKUP
    if not _CORNER_LOOKUP and VAL_CORNER_COLORS is not None:
        _CORNER_LOOKUP, _EDGE_LOOKUP = _build_lookups()

    # Optional deep topological validation using CubeValidator (handles objects and dicts)
    validator = _CubeValidator()
    if hasattr(validator, "validate"):
        validation_res = validator.validate(cube)
        is_valid = True
        errors = []
        
        if isinstance(validation_res, dict):
            is_valid = validation_res.get("valid", True)
            errors = validation_res.get("errors", [])
        else:
            is_valid = getattr(validation_res, "valid", True)
            errors = getattr(validation_res, "errors", [])

        if not is_valid:
            raise ValueError(f"Invalid CubeState topology: {errors}")

    corners: list[Any] = []
    for slot_idx, facelets in enumerate(CORNER_FACELETS):
        colors: list[str] = [
            str(cube.faces[face][row][col]).lower()
            for face, row, col in facelets
        ]
        color_set = frozenset(colors)
        if color_set not in _CORNER_LOOKUP:
            raise ValueError(
                f"Unrecognized corner piece at slot {slot_idx} with colors {colors} (set: {color_set})"
            )
        piece_idx  = _CORNER_LOOKUP[color_set]
        orientation = _corner_orientation(colors, facelets)
        corners.append(_CornerCubie(piece=piece_idx, orientation=orientation))

    edges: list[Any] = []
    for slot_idx, facelets in enumerate(EDGE_FACELETS):
        colors = [
            str(cube.faces[face][row][col]).lower()
            for face, row, col in facelets
        ]
        color_set = frozenset(colors)
        if color_set not in _EDGE_LOOKUP:
            raise ValueError(
                f"Unrecognized edge piece at slot {slot_idx} with colors {colors} (set: {color_set})"
            )
        piece_idx  = _EDGE_LOOKUP[color_set]
        orientation = _edge_orientation(colors, facelets)
        edges.append(_EdgeCubie(piece=piece_idx, orientation=orientation))

    return _CubieState(corners=corners, edges=edges)


# ===========================================================================
# CubieState → CubeState
# ===========================================================================

def cubiestate_to_cubestate(cubie: "CubieState") -> "CubeState":
    """
    Convert a CubieState (piece + orientation) to a CubeState (sticker grid).
    """
    _require_imports()

    faces: dict[str, list[list[str]]] = {
        face: [[""] * 3 for _ in range(3)] for face in _FACE_NAMES
    }
    for face, color in _FACE_TO_COLOR.items():
        faces[face][1][1] = color

    # ---- corners ----
    for slot_idx, facelets in enumerate(CORNER_FACELETS):
        corner      = cubie.corners[slot_idx]
        piece_idx   = corner.piece
        orientation = corner.orientation

        if orientation not in (0, 1, 2):
            raise ValueError(
                f"Corner slot {slot_idx}: invalid orientation {orientation}"
            )

        canonical  = CORNER_PIECE_CANONICAL[piece_idx]
        piece_is_d = piece_idx >= 4
        slot_is_d  = facelets[0][0] == "D"

        perm    = CORNER_PERM_TABLE[(piece_is_d, slot_is_d, orientation)]
        rotated = (canonical[perm[0]], canonical[perm[1]], canonical[perm[2]])

        for (face, row, col), color in zip(facelets, rotated):
            faces[face][row][col] = color

    # ---- edges ----
    for slot_idx, facelets in enumerate(EDGE_FACELETS):
        edge        = cubie.edges[slot_idx]
        piece_idx   = edge.piece
        orientation = edge.orientation

        if orientation not in (0, 1):
            raise ValueError(
                f"Edge slot {slot_idx}: invalid orientation {orientation}"
            )

        canonical_edge = EDGE_PIECE_CANONICAL[piece_idx]
        if orientation == 0:
            rotated_edge = canonical_edge
        else:
            rotated_edge = (canonical_edge[1], canonical_edge[0])

        for (face, row, col), color in zip(facelets, rotated_edge):
            faces[face][row][col] = color

    return _CubeState(faces)


# ===========================================================================
# Convenience re-exports from move.py
# ===========================================================================

def apply_algorithm(cube: "CubeState", algorithm: str) -> "CubeState":
    if _move_module is None:
        raise RuntimeError("move.py could not be imported.")
    return _move_module.apply_algorithm(cube, algorithm)

def apply_algorithm_cubie(cube: "CubieState", algorithm: str) -> "CubieState":
    if _move_module is None:
        raise RuntimeError("move.py could not be imported.")
    return _move_module.apply_algorithm_cubie(cube, algorithm)

def invert_algorithm(algorithm: str) -> str:
    if _move_module is None:
        raise RuntimeError("move.py could not be imported.")
    return _move_module.invert_algorithm(algorithm)


# ===========================================================================
# Test helpers
# ===========================================================================

def _create_solved_cubestate() -> "CubeState":
    if _CubeState is None:
        raise RuntimeError(CUBE_STATE_IMPORT_ERROR)
    return _CubeState({
        face: [[color] * 3 for _ in range(3)]
        for face, color in _FACE_TO_COLOR.items()
    })

def _create_solved_cubiestate() -> "CubieState":
    if _CubieState is None:
        raise RuntimeError(CUBIE_IMPORT_ERROR)
    return _CubieState()

def _cubiestate_equal(a: "CubieState", b: "CubieState") -> bool:
    for i in range(8):
        if a.corners[i].piece       != b.corners[i].piece:       return False
        if a.corners[i].orientation != b.corners[i].orientation: return False
    for i in range(12):
        if a.edges[i].piece         != b.edges[i].piece:         return False
        if a.edges[i].orientation   != b.edges[i].orientation:   return False
    return True

def _cubestate_equal(a: "CubeState", b: "CubeState") -> bool:
    for face in _FACE_NAMES:
        for row in range(3):
            for col in range(3):
                if a.faces[face][row][col] != b.faces[face][row][col]:
                    return False
    return True


# ===========================================================================
# Tests
# ===========================================================================

_ALGORITHMS: tuple[str, ...] = (
    "R", "U", "F", "D", "L", "B",
    "R U R' U'",
    "R U R' U' F2 L D",
    "R U R' U' F2 L D B R2 U2",
    "F R U R' U' F'",
    "R2 U2 F2 D2 L2 B2",
)

def _test_solved_cubestate_to_cubiestate() -> bool:
    cube   = _create_solved_cubestate()
    cubie  = cubestate_to_cubiestate(cube)
    solved = _create_solved_cubiestate()
    passed = _cubiestate_equal(cubie, solved)
    print("  Solved CubeState -> CubieState:", "PASS" if passed else "FAIL")
    return passed

def _test_solved_cubiestate_to_cubestate() -> bool:
    cubie  = _create_solved_cubiestate()
    cube   = cubiestate_to_cubestate(cubie)
    solved = _create_solved_cubestate()
    passed = _cubestate_equal(cube, solved)
    print("  Solved CubieState -> CubeState:", "PASS" if passed else "FAIL")
    return passed

def _test_round_trips() -> bool:
    if _move_module is None:
        print("  Round-trip tests skipped: move.py not available.")
        return True
    solved = _create_solved_cubestate()
    all_passed = True
    print("  Round-trip tests (CubeState -> CubieState -> CubeState):")
    for alg in _ALGORITHMS:
        try:
            scrambled = _move_module.apply_algorithm(solved, alg)
            converted = cubestate_to_cubiestate(scrambled)
            restored  = cubiestate_to_cubestate(converted)
            passed    = _cubestate_equal(scrambled, restored)
        except Exception as exc:
            print(f"    {alg}: FAIL ({exc})")
            all_passed = False
            continue
        print(f"    {alg}:", "PASS" if passed else "FAIL")
        if not passed: all_passed = False
    return all_passed

def _test_consistency() -> bool:
    if _move_module is None:
        print("  Consistency tests skipped: move.py not available.")
        return True
    solved_cube  = _create_solved_cubestate()
    solved_cubie = _create_solved_cubiestate()
    all_passed   = True
    print("  Consistency tests (CubeState move == CubieState move via converter):")
    for alg in _ALGORITHMS:
        try:
            moved_cube     = _move_module.apply_algorithm(solved_cube, alg)
            cubie_via_cube = cubestate_to_cubiestate(moved_cube)
            cubie_direct   = _move_module.apply_algorithm_cubie(solved_cubie, alg)
            passed         = _cubiestate_equal(cubie_via_cube, cubie_direct)
        except Exception as exc:
            print(f"    {alg}: FAIL ({exc})")
            all_passed = False
            continue
        print(f"    {alg}:", "PASS" if passed else "FAIL")
        if not passed: all_passed = False
    return all_passed

def _test_inverse_round_trip() -> bool:
    if _move_module is None:
        print("  Inverse round-trip tests skipped: move.py not available.")
        return True
    solved = _create_solved_cubestate()
    all_passed = True
    print("  Inverse round-trip tests (scramble + inverse -> solved):")
    for alg in _ALGORITHMS:
        try:
            inverse   = _move_module.invert_algorithm(alg)
            scrambled = _move_module.apply_algorithm(solved, alg)
            cubie_sc  = cubestate_to_cubiestate(scrambled)
            cubie_res = _move_module.apply_algorithm_cubie(cubie_sc, inverse)
            restored  = cubiestate_to_cubestate(cubie_res)
            passed    = _cubestate_equal(solved, restored)
        except Exception as exc:
            print(f"    {alg}: FAIL ({exc})")
            all_passed = False
            continue
        print(f"    {alg}:", "PASS" if passed else "FAIL")
        if not passed: all_passed = False
    return all_passed

def _test_immutability() -> bool:
    cube_orig  = _create_solved_cubestate()
    cubie_orig = _create_solved_cubiestate()
    cube_snap  = _create_solved_cubestate()
    cubie_snap = _create_solved_cubiestate()
    cubestate_to_cubiestate(cube_orig)
    cubiestate_to_cubestate(cubie_orig)
    cube_ok  = _cubestate_equal(cube_orig, cube_snap)
    cubie_ok = _cubiestate_equal(cubie_orig, cubie_snap)
    print("  CubeState unchanged after conversion:",  cube_ok)
    print("  CubieState unchanged after conversion:", cubie_ok)
    return cube_ok and cubie_ok

def _test_validation() -> bool:
    if _move_module is None:
        print("  Validation tests skipped: move.py not available.")
        return True
    solved = _create_solved_cubestate()
    all_passed = True
    print("  Validation tests (converted CubieState passes cubie.py validate()):")
    for alg in _ALGORITHMS:
        try:
            scrambled = _move_module.apply_algorithm(solved, alg)
            cubie_sc  = cubestate_to_cubiestate(scrambled)
            result    = cubie_sc.validate()
            passed    = result.get("valid", False)
        except Exception as exc:
            print(f"    {alg}: FAIL ({exc})")
            all_passed = False
            continue
        errs   = [] if passed else result.get("errors", [])
        suffix = "" if passed else f" ({', '.join(errs)})"
        print(f"    {alg}:", ("PASS" if passed else "FAIL") + suffix)
        if not passed: all_passed = False
    return all_passed


# ===========================================================================
# Main
# ===========================================================================

def main() -> None:
    print("=" * 40)
    print("CubeAI Cubie Converter")
    print("=" * 40)
    print()

    all_passed = True

    print("Solved-state tests:")
    if not _test_solved_cubestate_to_cubiestate(): all_passed = False
    if not _test_solved_cubiestate_to_cubestate(): all_passed = False
    print()

    if not _test_round_trips():        all_passed = False
    print()
    if not _test_consistency():        all_passed = False
    print()
    if not _test_inverse_round_trip(): all_passed = False
    print()
    if not _test_validation():         all_passed = False
    print()

    print("Immutability tests:")
    if not _test_immutability(): all_passed = False
    print()

    print("=" * 40)
    print("Converter tests:", "PASSED" if all_passed else "FAILED")
    print("=" * 40)


if __name__ == "__main__":
    main()